### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by kazBrainz** [afunmibi/mrkazim#1]
It is not a standard design practice for the button to sit on the margin/border as seen under the 'Contact Us' section. We can increase the margin bottom or padding bottom as the case may be. Also, the 'Back to top' can be transposed into a button. Well done sir!

**Comment by afunmibi** [comment]
Yes sir. Thank you for all the observations. i will surely correct them

**Comment by kazBrainz** [comment]
ok
